ENV:
  TOTAL_OBSTACLES: 10
  SEEN_OBSTACLES: 10
  MAX_VEL: 10.0
  DYNAMIC_OBSTACLES: True
  OBSTACLES_SPEED_FACTOR: 0.75

  GOAL_REWARD: 1.0
  CRASH_REWARD: 0.0

MODEL:
  OUNOISE_SIGMA: 0.1

TRAIN:
  TOTAL_STEPS: 4000000