ENV:
  TOTAL_OBSTACLES: 10
  SEEN_OBSTACLES: 10
  MAX_VEL: 10.0
  DYNAMIC_OBSTACLES: True
  CONSIDER_VELOCITIES: False
  CONSIDER_HISTORY: True   # Consider History of Obstacle Positions
  MIXED_STATIC_DYNAMIC: False
  OBSTACLES_SPEED_FACTOR: 0.75

  GOAL_REWARD: 1.0
  CRASH_REWARD: 0.0

  VARIANCE_OBSERVATION_NOISE: 0.0
  VARIANCE_ACTION_NOISE: 0.0

  STEPS_MODE_SCENARIO: 16


MODEL:
  OUNOISE_SIGMA: 0.1

TRAIN:
  TOTAL_STEPS: 4000000