ENV:
  TOTAL_OBSTACLES: 15
  SEEN_OBSTACLES: 10
  MAX_VEL: 5.0
  DYNAMIC_OBSTACLES: True
  OBSTACLES_SPEED_FACTOR: 0.75

  GOAL_REWARD: 1.0
  CRASH_REWARD: 0.0

  VARIANCE_OBSERVATION_NOISE: 0.0
  VARIANCE_ACTION_NOISE: 0.0

  STEPS_MODE_SCENARIO: 16


MODEL:
  OUNOISE_SIGMA: 0.1

TRAIN:
  TOTAL_STEPS: 4000000